# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.


#==============================================================================================================================

# #Workflow
# #YAML -> YAML aint a markup language

# #read and understand a series of steps or operations
# #this  can be read by the machine to automate tasks

# #key:value
# #key-title
# #value-website name
# title: Website Name
# description: A website for uploading content
# age: 30
# #string,arrays,objects

# #array
# tags:
#  - technology
#  - images
#  - creative
# #identation matters
# #spaces matters

# #objects
# address:
#   street: MG road
#   city: Banglore
#   state: KA

# #github actions
# #env variables
# value: ${{ env.VALUE }}
# variable: ${{ github.VARIABLE_NAME }}




#Github
#triggered on certain events
#on push,on pr request

#Workflow =>
#when to run
#on ->on trigger,on push to codebase, raising a pr to codebase
#how to run
#jobs -> a task that can be run
#Define a series of steps inside a job to execute the workflow
#steps:a sequence of tasks or actions that make up a job

name: Github action ofr
on:
  push:
    branches: [main]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Print Hello World
           run: node --version