
#Github
#triggered on certain events
#on push,on pr request

#Workflow =>
#when to run
#on ->on trigger,on push to codebase, raising a pr to codebase
#how to run
#jobs -> a task that can be run
#Define a series of steps inside a job to execute the workflow
#steps:a sequence of tasks or actions that make up a job

name: Github action ofr
on:
  push: 
    branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Print Hello World
           run: node --version
        - name: Print pwd
      